name: Build and Zip Project (excluding src and node_modules) on Release

on:
  release:
    types:
      - published

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.1"

      - name: Install dependencies
        run: npm install -ci

      - name: Run build script
        run: npm run build

      - name: Zip entire project excluding src and node_modules folder
        run: zip -r hafez.zip . -x "src/*" -x "node_modules/*"

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: hafez.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
